<a href="https://colab.research.google.com/github/Hritik-Ubale/SalesPredicition/blob/main/SalePrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#Reading the dataset
import pandas as pd
df = pd.read_csv('DigitalAd.csv')
print(df.shape)
print(df.head)

(199, 3)
<bound method NDFrame.head of      age  salary  result
0     19  139750       0
1     20  173200       1
2      4   79750       0
3     45  115000       1
4     40  141500       0
..   ...     ...     ...
194   48   90000       1
195    9  113600       1
196    4   92700       1
197    4   92000       0
198   34  189409       0

[199 rows x 3 columns]>


In [10]:
#REMOVED entries less than age 18
df = df[df['age'] > 18]
df.head

<bound method NDFrame.head of      age  salary  result
0     19  139750       0
1     20  173200       1
3     45  115000       1
4     40  141500       0
6     30  175000       1
..   ...     ...     ...
191   43  133700       0
192   19  122100       1
193   19   86250       0
194   48   90000       1
198   34  189409       0

[98 rows x 3 columns]>

In [11]:
#Dividing data into input and output
#SYNTAX => dataset.iloc[:,StartCol:EndCol]
X = df.iloc[:,:-1].values
X

array([[    19, 139750],
       [    20, 173200],
       [    45, 115000],
       [    40, 141500],
       [    30, 175000],
       [    45, 147765],
       [    21, 119250],
       [    20, 104800],
       [    19, 101000],
       [    38, 103450],
       [    37, 124750],
       [    39, 137000],
       [    31,  89565],
       [    36, 102580],
       [    34,  93904],
       [    24, 113068],
       [    21, 106294],
       [    35, 134885],
       [    20, 132261],
       [    22, 155750],
       [    41, 125196],
       [    23, 146500],
       [    23,  93418],
       [    40, 101299],
       [    38, 231545],
       [    19,  94384],
       [    25, 114778],
       [    40,  98193],
       [    23, 151768],
       [    25, 140096],
       [    28, 126621],
       [    23, 117704],
       [    33, 109785],
       [    22, 101000],
       [    35,  99418],
       [    28,  91412],
       [    45, 146856],
       [    29, 100131],
       [    35,  92391],
       [    28, 113398],


In [12]:
#output data
Y = df.iloc[:,-1].values
Y

array([0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0])

In [13]:
#Data Divided for training(75%) and testing(25%)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [14]:
# Feature Scaling - SO all methods contribute equally
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) #Extract more fetures
X_test = sc.transform(X_test)  #Act new to model

In [15]:
#Training Data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
#PREDICTING WHETHER CUSTOMER WILL BUY BASED ON AGE & SALARY
age = int(input("ENTER AGE : "))
salary = int(input("ENTER SALARY : "))
newCustomer = [[age,salary]]
result = model.predict(sc.transform(newCustomer))
print(result)
if result == 1:
  print("CUSTOMER WILL BUY")
else:
  print("CUSTOMER WILL NOT BUY")


ENTER AGE : 20
ENTER SALARY : 136000
[0]
CUSTOMER WILL NOT BUY


In [17]:
#Confusion matrix 
import numpy as np
y_pred = model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [1 0]]


In [18]:
#Evaluating model - Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("CONFUSION MATRIX")
print(cm)

print("ACCURACY OF THE MODEL: {0}%".format(accuracy_score(y_test, y_pred)* 100))

CONFUSION MATRIX
[[ 8  3]
 [12  2]]
ACCURACY OF THE MODEL: 40.0%
